{% set name = "pyapetnet" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyapetnet-{{ version }}.tar.gz
  sha256: 5f48e78fed2d4f609861df512ea033fe4f21105ad3e303dfc3d1b456abd3a6e4

build:
  number: 0
  noarch: python
  entry_points:
    - pyapetnet_predict_from_nifti=pyapetnet.predict_from_nifti:main
    - pyapetnet_predict_from_dicom=pyapetnet.predict_from_dicom:main
    - pyapetnet_list_models=pyapetnet.list_models:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - matplotlib-base >=3.1
    - nibabel >=3.0
    - pydicom >=2.0
    - pymirc >=0.29
    - tensorflow >=2.2
    - SimpleITK >=2.0

test:
  imports:
    - pyapetnet
  commands:
    - pip check
    - pyapetnet_predict_from_nifti --help
    - pyapetnet_predict_from_dicom --help
    - pyapetnet_list_models --help
  requires:
    - pip

about:
  home: https://github.com/gschramm/pyapetnet
  summary: a CNN for anatomy-guided deconvolution and denoising of PET images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
